name: build-and-test-windows

on:
  push:
    branches: ['canary', 'hl/turbopack-debugging']
  pull_request:
    types: [opened, synchronize]

env:
  NAPI_CLI_VERSION: 2.16.2
  TURBO_VERSION: 2.1.2
  NODE_LTS_VERSION: 20
  CARGO_PROFILE_RELEASE_LTO: 'true'
  TURBO_TEAM: 'vercel'
  TURBO_REMOTE_ONLY: 'true'

jobs:
  build-native:
    name: build-native
    runs-on:
      - 'self-hosted'
      - 'windows'
      - 'x64'
    timeout-minutes: 45
    steps:
      # we use checkout here instead of the build cache since
      # it can fail to restore in different OS'
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true
      - run: corepack enable

      # we always want to run this to set environment variables
      - name: Install Rust
        uses: ./.github/actions/setup-rust
        with:
          targets: x86_64-pc-windows-msvc

      - name: normalize versions
        run: node scripts/normalize-version-bump.js

      - name: Cache on ${{ github.ref_name }}
        uses: ijjk/rust-cache@turbo-cache-v1.0.8
        with:
          save-if: 'true'
          cache-provider: 'turbo'
          shared-key: build-x86_64-pc-windows-msvc-${{ hashFiles('.cargo/config.toml') }}

      - name: Clear native build
        run: Remove-Item packages/next-swc/native -Recurse -Force -ErrorAction SilentlyContinue

      - name: 'Build'
        # --env-mode loose is a breaking change required with turbo 2.x since Strict mode is now the default
        # TODO: we should add the relevant envs later to to switch to strict mode
        run: |
          corepack enable
          npm i -g "@napi-rs/cli@${NAPI_CLI_VERSION}" "turbo@${TURBO_VERSION}"
          turbo run build-native-release -vvv --env-mode loose --remote-cache-timeout 90 --summarize -- -- --target x86_64-pc-windows-msvc
